FlexJobs.com Webscrape Script
4 different attempts at trying to scrape FlexJobs.

It seems that the FlexJobs website is blocking the scraper due to their security policies.

[0413/002602.266:ERROR:cert_verify_proc_builtin.cc(677)] CertVerifyProcBuiltin for pixel.rubiconproject.com failed:
----- Certificate i=0 (CN=*.rubiconproject.com,O=Magnite\, Inc.,L=Los Angeles,ST=California,C=US) -----
ERROR: Time is after notAfter

[0413/002602.266:ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -201